apiVersion: apps/v1
kind: Deployment
metadata:
  name: affluent
spec: 
  replicas: 10
  selector: 
    matchLabels:
      component:  testsubject
  template:
    metadata:
      labels:
        component:  testsubject
    spec:
      containers:
        - name: fluke
          image:  registry.au-syd.bluemix.net/temp_namespace/automation-tool-pod:34
          ports:
            - containerPort:  9090


