apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: nginx
labels:
app: webserver
annotations:
deployment.kubernetes.io/revision: "1"
spec:
replicas: 3
selector:
matchLabels:
app: webserver
strategy:
rollingUpdate:
maxSurge: 1
maxUnavailable: 1
type: RollingUpdate
template:
metadata:
labels:
app: webserver
spec:
containers:
- name: nginx
image: nginx:1.7.9
ports:
- containerPort: 80


# As a simple example, assume a
# Deployment is supporting three replicas and
# is set to
# maxSurge
# 2. In this scenario, there will be a total of five replicas available
# during the RollingUpdate.


# At the peak of the deployment, there will be three replicas with
# the old version of the Pods running and two with the new ver
# sion
# of the Pods running


