apiVersion: v1
kind: ConfigMap
metadata:
  name: mc3-nginx-conf
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        upstream webapp {
            server 127.0.0.1:5000;
        }

        server {
            listen 80;

            location / {
                proxy_pass         http://webapp;
                proxy_redirect     off;
            }
        }
    }



    
  # Step 1. Create a ConfigMap with the nginx configuration file. 
  # Incoming HTTP requests to port 80 will be forwarded to port 5000 on localhost:


  # Step 2. Create a multi-container Pod with the simple web app and nginx in separate containers.
  # Note that for the Pod, we define only nginx port 80. Port 5000 will not be accessible outside of the Pod.


  ###
  # Need to complete no running yet
  ###