apiVersion: v1
kind: Pod
metadata:
  name: mc3
  labels:
    app: mc3
spec:
  containers:
  - name: webapp
    image: training/webapp
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: mc3-nginx-conf


  # Step 1. Create a ConfigMap with the nginx configuration file. 
  # Incoming HTTP requests to port 80 will be forwarded to port 5000 on localhost:


  # Step 2. Create a multi-container Pod with the simple web app and nginx in separate containers.
  # Note that for the Pod, we define only nginx port 80. Port 5000 will not be accessible outside of the Pod.

  # Step 3. Kubectl expose pod mc3 --type=NodePort --port=80


#  kubectl describe service mc3
#  ...
#  NodePort:	<unset>	31418/TCP



