apiVersion: batch/v1
kind: Job
metadata:
  name: deleterestart
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "60"]
      restartPolicy: Never


# delete and pod will restart itself if job is not completed 