apiVersion: batch/v1
kind: Job
metadata:
  name: hellosimplejob
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Hello Kubernetes!!!"]
      restartPolicy: Never
